#!/usr/bin/env python3
"""Rebuild reference/ from the primary sources.

Every file under reference/ is generated by this script from a public,
citable source. Nothing in reference/ is written by hand, and nothing in it
is a summary: it is the text of the standard, converted from the publisher's
own markup to Markdown so it can be read and quoted offline.

Run:  python3 tools/build_reference.py [--offline]

--offline skips the network and rebuilds from tools/.cache/ if present.
Provenance (source URL, retrieval date, SHA-256 of the retrieved bytes and of
the generated file) is written beside each output.
"""
import argparse, hashlib, html, json, os, re, subprocess, sys, datetime, urllib.request

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
REF = os.path.join(ROOT, "reference")
CACHE = os.path.join(os.path.dirname(os.path.abspath(__file__)), ".cache")

SOURCES = {
    "osha": {
        "url": "https://www.ecfr.gov/api/versioner/v1/full/2026-09-01/title-29.xml?part=1910&section=1910.1200",
        "headers": {"Accept": "application/xml", "Accept-Encoding": "gzip"},
        "cache": "osha-1910-1200.xml",
    },
    "eu878": {
        "url": "http://publications.europa.eu/resource/celex/32020R0878",
        "headers": {"Accept": "application/xhtml+xml", "Accept-Language": "eng",
                    "Accept-Encoding": "gzip"},
        "cache": "eu-2020-878.xhtml",
    },
    "clp": {
        "url": "http://publications.europa.eu/resource/celex/02008R1272-20260701",
        "headers": {"Accept": "application/xhtml+xml", "Accept-Language": "eng",
                    "Accept-Encoding": "gzip"},
        "cache": "clp-consolidated-20260701.xhtml",
    },
    # California Proposition 65, the statute only. The chapter is served whole by the state's own
    # legislative information system, which is why it can ship here at all: the OEHHA list of
    # listed chemicals is behind a bot challenge and cannot be fetched by a script, so it is not
    # here and reference/ca-prop-65/CONTEXT.md says what that costs an audit.
    "prop65": {
        "url": "https://leginfo.legislature.ca.gov/faces/codes_displayText.xhtml"
               "?lawCode=HSC&division=20.&title=&part=&chapter=6.6.&article=",
        "headers": {"Accept": "text/html", "User-Agent": "Mozilla/5.0"},
        "cache": "ca-hsc-chapter-6-6.html",
    },
}


def sha256(b):
    return hashlib.sha256(b).hexdigest()


def fetch(key, offline):
    src = SOURCES[key]
    path = os.path.join(CACHE, src["cache"])
    if offline:
        if not os.path.exists(path):
            sys.exit(f"offline: no cached source for {key} at {path}")
        return open(path, "rb").read()
    os.makedirs(CACHE, exist_ok=True)
    data = http_get(src["url"], src["headers"])
    open(path, "wb").write(data)
    return data


def http_get(url, headers):
    """urllib first; curl if the interpreter has no usable CA bundle. Salus has to run on
    whatever machine it was handed to, and a missing certificate store is not a reason to
    stop being able to refresh the standards."""
    try:
        req = urllib.request.Request(url, headers={"User-Agent": "Salus/1.0", **headers})
        with urllib.request.urlopen(req, timeout=180) as r:
            data = r.read()
            if r.headers.get("Content-Encoding") == "gzip":
                import gzip
                data = gzip.decompress(data)
            return data
    except Exception as e:
        hs = []
        for k, v in headers.items():
            if k.lower() != "accept-encoding":
                hs += ["-H", f"{k}: {v}"]
        r = subprocess.run(["curl", "-sS", "-L", "--compressed", "-m", "180",
                            "-H", "User-Agent: Salus/1.0", *hs, url],
                           capture_output=True, timeout=240)
        if r.returncode != 0 or not r.stdout:
            raise RuntimeError(f"fetch failed for {url}: urllib said {e}; "
                               f"curl said {r.stderr.decode()[:200]}")
        return r.stdout


# ---------- markup -> text ----------

def _txt(node):
    node = re.sub(r"<(SU|sup)[^>]*>(.*?)</\1>", r"^\2", node, flags=re.S | re.I)
    node = re.sub(r"<[^>]+>", " ", node)
    node = html.unescape(node)
    node = node.replace("\xa0", " ")
    return re.sub(r"[ \t\r\n]+", " ", node).strip()


def tables_to_md(block):
    """Convert every <table> in block to a pipe table, leave the rest alone."""
    def one(m):
        tbl = m.group(0)
        rows = re.findall(r"<tr[^>]*>(.*?)</tr>", tbl, re.S | re.I)
        out, width = [], 0
        for r in rows:
            cells = [_txt(c) for c in re.findall(r"<t[dh][^>]*>(.*?)</t[dh]>", r, re.S | re.I)]
            if not any(cells):
                continue
            width = max(width, len(cells))
            out.append(cells)
        if not out:
            return ""
        lines = []
        for i, cells in enumerate(out):
            cells = cells + [""] * (width - len(cells))
            lines.append("| " + " | ".join(c.replace("|", "\\|") for c in cells) + " |")
            if i == 0:
                lines.append("| " + " | ".join(["---"] * width) + " |")
        return "\n\n" + "\n".join(lines) + "\n\n"
    return re.sub(r"<table[^>]*>.*?</table>", one, block, flags=re.S | re.I)


# eCFR block tags, longest name first so that an indent variant is never mistaken for its
# base tag. The publisher writes indented paragraphs as <P-2>, <FP-1>, <FP-2>: a pattern of
# `<(P|FP)[^>]*>` matches those openings too, because [^>]* swallows the "-2", and then hunts
# for a closing </P> or </FP> that belongs to a different element tens of thousands of
# characters away. Everything in between - headings, paragraphs, whole tables - is consumed as
# the text of one paragraph. That is what ran Appendices A and B together into single lines of
# 143,677 and 69,528 characters and made a citation into them unopenable. The closing tag must
# match the opening tag exactly, suffix included.
ECFR_BLOCK = re.compile(
    r"<(HEAD|HD1|HD2|HD3|HED|CAPTION|NOTE|FP-\d+|FP|P-\d+|P)(?:\s[^>]*)?>(.*?)</\1\s*>"
    r"|(\n\|[^\n]*\|)", re.S | re.I)


def ecfr_to_md(xml):
    """eCFR section XML -> Markdown, keeping the (a)(1)(i) numbering visible.

    One block element in, one line out. The appendices are numbered the same way the body is -
    B.6.1, C.2.4.5, A.7.2.3.1 - and each of those provisions is its own element in the source,
    so keeping the elements apart is the whole of what makes them citable.
    """
    body = tables_to_md(xml.decode("utf-8", "replace"))
    out = []
    for m in ECFR_BLOCK.finditer(body):
        if m.group(3):
            out.append(m.group(3).strip())
            continue
        tag, inner = m.group(1).upper(), _txt(m.group(2))
        if not inner:
            continue
        if tag == "HEAD":
            out.append("\n# " + inner + "\n")
        elif tag in ("HD1", "HED", "CAPTION"):
            out.append("\n## " + inner + "\n")
        elif tag in ("HD2", "HD3"):
            out.append("\n### " + inner + "\n")
        elif tag == "NOTE":
            out.append("> " + inner)
        else:
            # P, P-n, FP, FP-n. The indent variants carry ordinary provision text, so they are
            # written the same way a <P> is - one paragraph per line - not given a style of
            # their own.
            out.append(inner)
    return "\n\n".join(out)


def eurlex_to_md(xhtml):
    body = xhtml.decode("utf-8", "replace")
    body = re.sub(r"<(script|style)[^>]*>.*?</\1>", " ", body, flags=re.S | re.I)
    body = tables_to_md(body)
    chunks = re.split(r"(?i)</?(?:p|div|h[1-6]|br)[^>]*>", body)
    out, seen_blank = [], False
    for c in chunks:
        if c.lstrip().startswith("|"):
            out.append(c.strip())
            seen_blank = False
            continue
        t = _txt(c)
        if not t:
            continue
        if re.fullmatch(r"(ANNEX II|ANNEX|Article \d+|SECTION \d+:.*)", t):
            out.append("\n## " + t + "\n")
        elif re.fullmatch(r"\d+(\.\d+)*\.?\s+[A-Z].{0,90}", t):
            out.append("\n### " + t + "\n")
        else:
            out.append(t)
        seen_blank = False
    return "\n\n".join(out)


# ---------- CLP Annex VI: notes + only the rows the corpus needs ----------

def clp_notes(xhtml):
    """Annex VI Part 1, the Notes list. Anchored on its own heading, not on 'Note A:',
    which also occurs inside Table 3 rows thousands of lines earlier."""
    t = xhtml.decode("utf-8", "replace")
    i = t.find("Notes relating to the identification, classification and labelling of substances")
    if i < 0:
        return "\n\n(notes section not found in source)\n"
    j = t.find("Notes relating to the classification", i + 100)
    if j < 0:
        j = i + 60000
    seg = tables_to_md(t[i:j])
    out = []
    for part in re.split(r"(?i)</?(?:p|div|br|tr)[^>]*>", seg):
        if part.lstrip().startswith("|"):
            out.append(part.strip())
            continue
        x = _txt(part)
        if not x or x in ("—————",) or re.fullmatch(r"[\u25b6\u25bc]?\s*M?\d*\s*", x):
            continue
        m = re.match(r"^(Note [A-Z]+)\s*:\s*(.*)$", x)
        if m:
            out.append("\n### " + m.group(1) + "\n")
            if m.group(2):
                out.append(m.group(2))
        else:
            out.append(x)
    # collapse repeats the publisher's markup produces
    ded, prev = [], None
    for x in out:
        if x != prev:
            ded.append(x)
        prev = x
    return "\n\n".join(ded)


def clp_rows(xhtml, wanted_cas):
    """Pull the Table 3 rows keyed by any identifier the corpus mentions - CAS number or
    Annex VI Index number."""
    t = xhtml.decode("utf-8", "replace")
    rows, seen = [], set()
    for cas in sorted(wanted_cas):
        pos = 0
        while True:
            i = t.find(">" + cas + "<", pos)
            if i < 0:
                break
            pos = i + 1
            s = t.rfind("<tr", 0, i)
            e = t.find("</tr>", i)
            if s < 0 or e < 0:
                continue
            cells = [_txt(c) for c in re.findall(r"<td[^>]*>(.*?)</td>", t[s:e], re.S | re.I)]
            if len(cells) < 8 or not re.fullmatch(r"\d{3}-\d{3}-\d{2}-\d", cells[0] or ""):
                continue
            if cells[0] in seen:
                break
            seen.add(cells[0])
            rows.append(cells)
            break
    return sorted(rows, key=lambda r: r[0])


CLP_COLS = ["Index No", "International Chemical Identification", "EC No", "CAS No",
            "Hazard Class and Category Code(s)", "Hazard Statement Code(s)",
            "Pictogram, Signal Word Code(s)", "Hazard statement code(s)",
            "Suppl. Hazard statement code(s)", "Specific Conc. Limits, M-factors, ATE", "Notes"]


def corpus_cas(pdf_dir):
    """Every CAS number and every Annex VI Index number that appears in the shipped test
    sheets. Both are needed: a group entry such as "antimony compounds" carries an Index
    number and no CAS, so a CAS-only sweep would silently miss it."""
    found = set()
    if not os.path.isdir(pdf_dir):
        return found
    for name in sorted(os.listdir(pdf_dir)):
        if not name.lower().endswith(".pdf"):
            continue
        try:
            txt = subprocess.run(["pdftotext", "-layout", os.path.join(pdf_dir, name), "-"],
                                 capture_output=True, text=True, timeout=120).stdout
        except Exception:
            continue
        found |= set(re.findall(r"\b\d{2,7}-\d{2}-\d\b", txt))
        found |= set(re.findall(r"\b\d{3}-\d{3}-\d{2}-\d\b", txt))
    return found


def leginfo_to_md(raw):
    """California Health and Safety Code, chapter 6.6, out of leginfo's own markup.

    The state serves each section as an <h6> carrying the section number, followed by the section's
    text and the italic note recording when it was enacted or amended. That structure is the whole
    converter: one heading per section, the text under it, and nothing invented in between."""
    html_text = raw.decode("utf-8", errors="replace")
    body = re.search(r'<div id="manylawsections">(.*?)</body>', html_text, re.S | re.I)
    if not body:
        raise RuntimeError("leginfo markup changed: no id='manylawsections' block")
    block = body.group(1)

    def clean(fragment):
        fragment = re.sub(r"<br\s*/?>", "\n", fragment, flags=re.I)
        fragment = re.sub(r"<[^>]+>", " ", fragment)
        fragment = html.unescape(fragment)
        lines = [" ".join(line.split()) for line in fragment.split("\n")]
        return "\n".join(line for line in lines if line)

    chapter = re.search(r"<h5[^>]*>\s*<b>(.*?)</b>", block, re.S | re.I)
    out = ["# California Proposition 65 — the statute",
           "",
           "Health and Safety Code, Division 20, "
           + (clean(chapter.group(1)) if chapter else "Chapter 6.6") + ".",
           "",
           "This folder holds the **obligation** and not the list. The chemicals \"known to the "
           "state\" are published by OEHHA under Section 25249.8 and are not shipped here — "
           "`reference/CONTEXT.md` says what that means for an audit.",
           ""]
    parts = re.split(r'<h6[^>]*>\s*<a[^>]*>\s*([\d.]+?)\.?\s*</a>\s*</h6>', block)
    for number, text in zip(parts[1::2], parts[2::2]):
        out.append(f"## Section {number}")
        out.append("")
        out.append(clean(text))
        out.append("")
    if len(parts) < 3:
        raise RuntimeError("leginfo markup changed: no section headings found")
    return "\n".join(out).rstrip() + "\n"


def write(path, text, source_url, raw, retrieved):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    open(path, "w", encoding="utf-8").write(text)
    prov = os.path.join(os.path.dirname(path), "PROVENANCE.md")
    entry = {
        "file": os.path.basename(path),
        "source_url": source_url,
        "retrieved_utc": retrieved,
        "source_sha256": sha256(raw),
        "source_bytes": len(raw),
        "output_sha256": sha256(text.encode("utf-8")),
        "output_bytes": len(text.encode("utf-8")),
        "generated_by": "tools/build_reference.py",
    }
    existing = {}
    if os.path.exists(prov):
        m = re.search(r"```json\n(.*?)\n```", open(prov, encoding="utf-8").read(), re.S)
        if m:
            try:
                existing = {e["file"]: e for e in json.loads(m.group(1))}
            except Exception:
                existing = {}
    existing[entry["file"]] = entry
    body = ("# Provenance\n\n"
            "Every file in this folder is generated by `tools/build_reference.py` from the\n"
            "publisher's own markup. Re-run the script and the hashes below must reproduce.\n"
            "If they do not, the source has changed and the audit rules that cite it are stale.\n\n"
            "```json\n" + json.dumps(list(existing.values()), indent=2) + "\n```\n")
    open(prov, "w", encoding="utf-8").write(body)
    print(f"  wrote {os.path.relpath(path, ROOT)}  ({len(text):,} chars)")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--offline", action="store_true")
    ap.add_argument("--only", action="append", choices=sorted(SOURCES),
                    help="rebuild one standard and leave the others exactly as they are. "
                         "Repeatable. Without it, all three are rebuilt.")
    a = ap.parse_args()
    want = set(a.only) if a.only else set(SOURCES)
    now = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

    if "osha" in want:
        print("OSHA 29 CFR 1910.1200 ...")
        raw = fetch("osha", a.offline)
        write(os.path.join(REF, "us-osha-hcs", "29-cfr-1910-1200.md"),
              ecfr_to_md(raw), SOURCES["osha"]["url"], raw, now)

    if "eu878" in want:
        print("EU Regulation 2020/878 ...")
        raw = fetch("eu878", a.offline)
        write(os.path.join(REF, "eu-2020-878", "regulation-2020-878.md"),
              eurlex_to_md(raw), SOURCES["eu878"]["url"], raw, now)

    if "prop65" in want:
        print("California Proposition 65 (Health and Safety Code, chapter 6.6) ...")
        raw = fetch("prop65", a.offline)
        write(os.path.join(REF, "ca-prop-65", "health-safety-code-chapter-6-6.md"),
              leginfo_to_md(raw), SOURCES["prop65"]["url"], raw, now)

    if "clp" in want:
        print("CLP Annex VI (consolidated 2026-07-01) ...")
        raw = fetch("clp", a.offline)
        write(os.path.join(REF, "eu-clp-annex-vi", "annex-vi-notes.md"),
              "# CLP Annex VI, Part 1 — Notes relating to the identification, "
              "classification and labelling of substances\n\n"
              "Source: Regulation (EC) No 1272/2008, consolidated text in force from 2026-07-01.\n"
              + clp_notes(raw), SOURCES["clp"]["url"], raw, now)

        cas = corpus_cas(os.path.join(ROOT, "test-cases", "sds"))
        print(f"  {len(cas)} distinct CAS/Index numbers found in the shipped test sheets")
        rows = clp_rows(raw, cas)
        md = ["# CLP Annex VI, Table 3 — harmonised classification rows cited by this auditor",
              "",
              "Source: Regulation (EC) No 1272/2008, consolidated text in force from 2026-07-01.",
              "",
              "This is an **extract**, not the whole table. Annex VI Table 3 holds several thousand",
              "entries; shipping all of them would make this folder unreadable and would not make any",
              "finding more checkable. The rows below are exactly those whose CAS number appears in a",
              "sheet under `test-cases/sds/`, matched by CAS number or by Index number, so every finding",
              "this auditor makes about a harmonised",
              "classification can be opened and checked here.",
              "",
              f"Rows: **{len(rows)}**, selected from {len(cas)} distinct CAS and Index numbers "
              "found in the corpus.",
              "",
              "A substance absent from this extract is not thereby unclassified — it may simply have",
              "no harmonised entry, in which case the supplier self-classifies and this auditor cannot",
              "call that classification wrong. See `identity.md`, Declared blind spots.",
              ""]
        if rows:
            md.append("| " + " | ".join(CLP_COLS) + " |")
            md.append("| " + " | ".join(["---"] * len(CLP_COLS)) + " |")
            for r in rows:
                r = (r + [""] * len(CLP_COLS))[:len(CLP_COLS)]
                md.append("| " + " | ".join(c.replace("|", "\\|") for c in r) + " |")
        write(os.path.join(REF, "eu-clp-annex-vi", "annex-vi-table-3-extract.md"),
              "\n".join(md) + "\n", SOURCES["clp"]["url"], raw, now)
    print("done")


if __name__ == "__main__":
    main()
