#!/usr/bin/env python3
"""Run the canonical finding example in rules.md through Gate 2.

    python3 tools/test_docs_example.py

rules.md contains the worked example an auditor reads to learn how a finding must be written.
An example that the gate would reject is worse than no example: it teaches a shape that cannot
ship, and the person who follows it finds out only after doing the work.

So the example is not decoration here. This script lifts it straight out of rules.md, wraps it
in the smallest report that satisfies the report shape, and runs the real citation gate over it.
If the documentation drifts away from the standard - a superseded revision, a quote edited in
the file but not in the example - this fails.
"""
import os, re, subprocess, sys, tempfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
START = "    [F-03] [STANDARD]"
STOP = "Two details in that example"


def main():
    rules = open(os.path.join(ROOT, "rules.md"), encoding="utf-8").read()
    if START not in rules or STOP not in rules:
        print("FAIL  could not find the worked example in rules.md — the anchors moved")
        return 1
    block = rules[rules.index(START):rules.index(STOP)].strip("\n")

    finding = "### " + block.lstrip()
    passing = re.sub(r"\[F-03\]", "[P-01]", finding, count=1)

    # The probe carries the jurisdiction row every real report carries, and it carries EU
    # because the worked example cites CLP Annex VI, which only an EU run may open. Both report
    # gates now read that row: Gate 2 to decide which corpus the findings may stand on, Gate 3
    # to check the report names a regime at all. A probe without it would be testing the example
    # against a shape no report may ship in.
    report = "\n".join([
        "# Probe report — generated by tools/test_docs_example.py, not a real audit",
        "",
        "| | |", "| --- | --- |",
        "| Jurisdiction (from `config/jurisdiction.md`) | EU |",
        "| Standard applied | Commission Regulation (EU) 2020/878, with CLP Annex VI |",
        "", "## VERDICT: DOES NOT CONFORM", "",
        finding, "", "## What passed", "", passing, "",
        "## Declared blind spots", "",
        "- This is a probe, not an audit of any sheet.", "",
    ])

    with tempfile.NamedTemporaryFile("w", suffix=".md", delete=False, encoding="utf-8") as fh:
        fh.write(report)
        path = fh.name
    try:
        for gate in ("verify_citations.py", "validate_report.py"):
            r = subprocess.run([sys.executable, os.path.join(ROOT, "tools", gate), path],
                               capture_output=True, text=True, cwd=ROOT)
            tail = r.stdout.strip().split("\n")[-1] if r.stdout.strip() else r.stderr.strip()[:200]
            print(f"{'PASS' if r.returncode == 0 else 'FAIL'}  {gate}: {tail}")
            if r.returncode != 0:
                print(r.stdout.strip())
                return 1
    finally:
        os.unlink(path)
    print("\nThe example in rules.md passes the gates it teaches.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
