#!/usr/bin/env python3
"""Run the canonical finding example in rules.md through Gate 2.

    python3 tools/test_docs_example.py

rules.md contains the worked example an auditor reads to learn how a finding must be written.
An example that the gate would reject is worse than no example: it teaches a shape that cannot
ship, and the person who follows it finds out only after doing the work.

So the example is not decoration here. This script lifts it straight out of rules.md, wraps it
in the smallest report that satisfies the report shape, and runs the real citation gate over it.
If the documentation drifts away from the standard - a superseded revision, a quote edited in
the file but not in the example - this fails.
"""
import os, re, subprocess, sys, tempfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
START = "    [F-03] [STANDARD]"
STOP = "Two details in that example"


def main():
    rules = open(os.path.join(ROOT, "rules.md"), encoding="utf-8").read()
    if START not in rules or STOP not in rules:
        print("FAIL  could not find the worked example in rules.md — the anchors moved")
        return 1
    block = rules[rules.index(START):rules.index(STOP)].strip("\n")

    finding = "### " + block.lstrip()
    passing = re.sub(r"\[F-03\]", "[P-01]", finding, count=1)

    report = "\n".join([
        "# Probe report — generated by tools/test_docs_example.py, not a real audit",
        "", "## VERDICT: DOES NOT CONFORM", "",
        finding, "", "## What passed", "", passing, "",
        "## Declared blind spots", "",
        "- This is a probe, not an audit of any sheet.", "",
    ])

    with tempfile.NamedTemporaryFile("w", suffix=".md", delete=False, encoding="utf-8") as fh:
        fh.write(report)
        path = fh.name
    try:
        for gate in ("verify_citations.py", "validate_report.py"):
            # Deliberately NOT cwd=ROOT. The probe report is written to a temporary directory
            # outside the repository and the gates are invoked from wherever this script was
            # started, so this doubles as the regression test for a gate that used to resolve
            # `reference/...` against the caller's working directory.
            r = subprocess.run([sys.executable, os.path.join(ROOT, "tools", gate), path],
                               capture_output=True, text=True)
            tail = r.stdout.strip().split("\n")[-1] if r.stdout.strip() else r.stderr.strip()[:200]
            print(f"{'PASS' if r.returncode == 0 else 'FAIL'}  {gate}: {tail}")
            if r.returncode != 0:
                print(r.stdout.strip())
                return 1
    finally:
        os.unlink(path)
    print("\nThe example in rules.md passes the gates it teaches.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
