#!/usr/bin/env python3
"""Gate 0 — is the shipped corpus still the corpus that was generated?

    python3 tools/verify_reference.py [--reference reference] [--quiet]

`reference/` is generated by `tools/build_reference.py`, and every generated folder carries a
`PROVENANCE.md` recording the SHA-256 of each file it wrote. Until this script existed those
hashes were decoration: nothing read them. The rule "reference/ is generated, never hand-edited"
was prose, and prose does not hold a file still. This recomputes every recorded hash and fails by
name on a changed file, a missing file, or a file that appears in a generated folder without a
provenance record.

It is the gate the other gates stand on. Gate 2 asks whether a quoted provision appears in the
standard the finding names; that question is worth exactly as much as the standard being the one
that was downloaded. Edit one date in `reference/` and Gate 2 will confirm the edit and blame the
report for disagreeing with it. So Gate 2 calls this first, and the check is cheap enough
(~450 KB, a few milliseconds) that a judge verifying one report never notices the cost.

To see it work, change one character in a shipped standard and re-run.

Checks:
  1. every folder under reference/ that ships files has a PROVENANCE.md, and it parses
  2. every file a PROVENANCE.md records exists, and its SHA-256 is the one recorded
  3. no unrecorded file sits in a generated folder — a hand-written file dropped in beside the
     regulation is loaded by Gate 2 as though it were regulatory text
  4. nothing unaccounted-for sits at the top of reference/, for the same reason

Limits, and they matter:

  * Only the OUTPUT hash is checkable here. `PROVENANCE.md` also records the SHA-256 of the
    publisher's bytes, but those bytes are not shipped — `tools/.cache/` is gitignored — so this
    script cannot confirm that the source hash describes anything real. That check needs a
    network and is `tools/build_reference.py`: re-run it and the recorded hashes must reproduce.

  * `PROVENANCE.md` is not self-authenticating. Anyone who edits a standard can recompute the
    hash and rewrite the record, and this script would then pass. What it catches is the edit
    that was NOT accompanied by a rewritten record; what catches the other kind is the diff,
    because both files are committed and a provenance rewrite is loud in the history. The pair
    is the mechanism. Neither half is sufficient alone, and this docstring is the place that
    says so rather than leaving a reader to assume otherwise.

  * Three files under reference/ are NOT generated output and are never hashed here:
    `STANDARDS-LEDGER.md` is maintained by a person — deciding a revision is in force is a legal
    reading, not a string comparison; `FRESHNESS-LOG.md` is written by `tools/check_freshness.py`
    on every online run; `CONTEXT.md` is documentation. Hashing them would freeze work that is
    supposed to move and would fail this gate every time a person did their job.

  * This says nothing about whether the standard is CURRENT. A faithfully preserved copy of a
    superseded regulation passes here and is still the wrong law. That is the ledger's question
    and `tools/check_freshness.py`'s.

  * Dotfiles are ignored. `.DS_Store` is not a claim about a standard.
"""
import argparse, hashlib, json, os, re, sys

# Files directly under reference/ that are not generated output. Each is listed with its owner
# because the reason they are excluded is not the same reason in each case.
NOT_GENERATED = {
    "CONTEXT.md": "documentation",
    "STANDARDS-LEDGER.md": "hand-maintained by a person",
    "FRESHNESS-LOG.md": "written by tools/check_freshness.py",
}


REPO_ROOT = os.path.dirname(os.path.dirname(os.path.realpath(__file__)))


def sha256_file(path):
    h = hashlib.sha256()
    with open(path, "rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def read_records(prov_path):
    """The JSON block build_reference.py writes into PROVENANCE.md, or an error string."""
    text = open(prov_path, encoding="utf-8").read()
    m = re.search(r"```json\n(.*?)\n```", text, re.S)
    if not m:
        return None, "holds no ```json provenance block"
    try:
        records = json.loads(m.group(1))
    except Exception as e:
        return None, f"provenance block is not valid JSON: {e}"
    if not isinstance(records, list) or not records:
        return None, "provenance block records no files"
    return records, None


def audit(refdir):
    """Recompute what PROVENANCE.md recorded. Returns (problems, stats).

    problems is a list of one-line strings, each naming a file. Empty means the corpus on disk
    is byte-for-byte the corpus that was generated.
    """
    problems, stats = [], {"provenance_files": 0, "verified": 0, "bytes": 0, "standards": []}

    if not os.path.isdir(refdir):
        return [f"{refdir}/ does not exist"], stats

    for name in sorted(os.listdir(refdir)):
        if name.startswith("."):
            continue
        path = os.path.join(refdir, name)
        if os.path.isfile(path) and name not in NOT_GENERATED:
            problems.append(
                f"{os.path.join(refdir, name)} — unaccounted for: it is neither generated output "
                f"nor one of the three known non-generated files, and Gate 2 would read it as a "
                f"standard")

    for name in sorted(os.listdir(refdir)):
        folder = os.path.join(refdir, name)
        if name.startswith(".") or not os.path.isdir(folder):
            continue

        shipped = set()
        for root, dirs, names in os.walk(folder):
            dirs[:] = [d for d in dirs if not d.startswith(".")]
            for n in names:
                if not n.startswith("."):
                    shipped.add(os.path.relpath(os.path.join(root, n), folder))

        prov = os.path.join(folder, "PROVENANCE.md")
        if not os.path.exists(prov):
            problems.append(f"{folder}/ ships {len(shipped)} file(s) and records no provenance: "
                            f"there is no PROVENANCE.md, so nothing in it can be checked")
            continue
        stats["provenance_files"] += 1
        shipped.discard("PROVENANCE.md")

        records, err = read_records(prov)
        if err:
            problems.append(f"{prov} — {err}")
            continue

        recorded, ok = set(), 0
        for rec in records:
            fname = rec.get("file")
            want = rec.get("output_sha256")
            if not fname or not want:
                problems.append(f"{prov} — a record names no file or no output_sha256")
                continue
            recorded.add(fname)
            target = os.path.join(folder, fname)
            if not os.path.exists(target):
                problems.append(f"{target} — recorded in PROVENANCE.md and MISSING from disk")
                continue
            got = sha256_file(target)
            size = os.path.getsize(target)
            if got != want:
                problems.append(
                    f"{target} — CHANGED since it was generated: recorded {want[:16]}…, "
                    f"found {got[:16]}… ({rec.get('output_bytes', '?')} bytes recorded, "
                    f"{size} on disk). Restore it with git, or rebuild with "
                    f"tools/build_reference.py; do not edit it")
                continue
            ok += 1
            stats["verified"] += 1
            stats["bytes"] += size

        for extra in sorted(shipped - recorded):
            problems.append(
                f"{os.path.join(folder, extra)} — present in a generated folder with no "
                f"provenance record. Either build_reference.py did not write it or a person did; "
                f"Gate 2 would quote from it as though it were the standard")

        stats["standards"].append((name, ok, len(records)))

    return problems, stats


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--reference", default=None,
                   help="corpus to check; defaults to reference/ beside this script. An "
                        "explicit path is resolved against YOUR working directory.")
    ap.add_argument("--quiet", action="store_true",
                    help="print nothing when the corpus verifies; exit code carries the answer")
    a = ap.parse_args()

    # Anchored on this script's own location, like every other gate here: the corpus a gate
    # checks is the one that ships with it, whatever directory the caller happens to be in.
    refdir = os.path.abspath(a.reference) if a.reference else os.path.join(REPO_ROOT, "reference")
    problems, stats = audit(refdir)

    if problems:
        for p in problems:
            print(f"FAIL  {p}")
        print(f"\n{len(problems)} problem(s). The corpus on disk is not the corpus that was "
              f"generated, so no gate that reads it can be believed. reference/ is generated "
              f"output: it is restored with git, not repaired by hand.")
        return 1

    if stats["provenance_files"] == 0:
        print(f"FAIL  no PROVENANCE.md anywhere under {refdir}/ — nothing here claims to "
              f"have been generated, so there is nothing to verify")
        return 2

    if a.quiet:
        return 0

    for name, ok, total in stats["standards"]:
        print(f"  OK  {name}: {ok}/{total} file(s) match the hashes recorded when they were "
              f"generated")
    for name, why in sorted(NOT_GENERATED.items()):
        if os.path.exists(os.path.join(refdir, name)):
            print(f"  --  {name}: not generated output ({why}) — not hashed, by design")
    print(f"\n{stats['verified']} file(s), {stats['bytes']:,} bytes, across "
          f"{stats['provenance_files']} standard(s). Every shipped standard is byte-for-byte the "
          f"file tools/build_reference.py produced, and nothing unrecorded has been added to a "
          f"generated folder.")
    print("The source hashes are not checked here — the publisher's bytes are not shipped. "
          "See this script's docstring.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
